services:
  - type: web
    name: water-monitor-websocket
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python water_monitor_iot_server.py
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health